ansible_become_pass: ENC[AES256_GCM,data:nxgVJZwA0rYNnCo70mBUtw==,iv:mEP8IoGVO975R5D/ke2Ntqm/c8MLrS39aCiltQ/8Ch0=,tag:RfXTY/axU2/gmFlCjd1GZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVDhtVTM5eTVxMjM5QWlO
            a0wyS05PYnNVMmdKK2NYY2NWcXVrTnd4UDJBCnJqRG9iaTJRVE1kalZhL1dBTUlH
            SnhCWXRtNjFFd09jeEpLTG1zQzFKVUkKLS0tIGhNLzRKZGY4OUVwQ296U3ZVOVNB
            Sm50b25XbU4yZ1B3amx4MjhTT1ZNcTAKo/ZwFRUvBL+zqcJ5gEQwLI/2UraItZs5
            /QH7I4JVKBt2FyI0roF6g7TUNqz+bOfv2rhUi6MV0jdy1Rz31iFHMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-30T04:45:49Z"
    mac: ENC[AES256_GCM,data:vv2iMZoamJ+TxsA/Fw5vKsBScUQ/ZGneTDJZ4mZnrWHyfQ6M5Z015nK6er4IIDC0JB/edI7tnJfKm2JsdQ/wuZq+kKwvwTQbYpAcL8sQ2UrrEh92+hVyQ0rWAz1vACwzi9nDt08sAdbs6E/OWdkisEXVMY+ihX9hPDoVk9VX+mk=,iv:Gs5onp6hab0qHOyB/xN7lIy0Yq7PMlKukXbjebA6W8o=,tag:Hiswks90gBJwWxyxJSSsDg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
