ansible_become_pass: ENC[AES256_GCM,data:WWN5N78Nf3+709GHUAawqw==,iv:h35punT+0hue41GMTadqfBz8gTbsxmfWRxh4jinP9Ck=,tag:s0bQP/4sxXj6IadjmflR0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTkVRMkE2bnVRTmR0Rlp1
            WEJzYlo1SGVkQUVRaWpWMDZtQm1DZDIrUW1vCjZVV1dJb01hajFKcnQyU0V2Mno0
            NTM5Wnc1QjVFWmJhd3BBTFN1aEw2OFkKLS0tIFJZWUk3eG9rUTl2cmJ6R2oycGRl
            c1p4eWlEZ0k0aGNheGtpSWtpRkFOaTAKCFCz6rljKvSN0Tr5+EpKkCuPs2D7BuB6
            3/I6j/hT2W3lL8mrsZFTQG4Fy/0hiqYcTj9L06N1GuEyEJUx11lLrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T01:15:29Z"
    mac: ENC[AES256_GCM,data:HGGdUKLJn++OX98mFW7BiFbFQA5N8qUnNzyeot4DHJYLqxqUbo0RxZKkN4MO4syNGZt4FlL3C5sbiQw4gnIV0/wD6iFHyleYHxtOk92vl0A2sN+OwYK4thjgAACfr6KKMpt/oK/LIh1FdBN2NccBJwrDmeMVSKIna/7AcRu/Hlc=,iv:qXcqqYsuTJgBI+CeEFL/6MTvI9GPL1mxejQnL64guSI=,tag:bsJcy0K/U60luqlbU7sccw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
