ansible_become_pass: ENC[AES256_GCM,data:2GPDSmTafXFVd7v+IV5IzA==,iv:QjkHXUfmYZXAtMxQhTm9WgsONViEKPNZP491o28Ka3g=,tag:Hq3z5lrokTlomQVQ5YRTAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET2tYSUtCVUNmUHhMMGZZ
            MGIybXJWbmVOL0hRdmM5SFVYdDB6V0JOMEJjCk9CaWpsU2tuRGd0bzNkQ0J4TDBE
            alhneHo3RkFWQUFuY3I4dWMxM2dHb2cKLS0tIE16WXF3MHRQRmRqTkNCN2t2V2xw
            dGo0ZWJaN0lhRWgxMDNySUxqaXJrenMKDodLg5snhXlvTNKR1JvZ7p5fuajA2qTH
            diRlVZuLdMuYcnUDdVHPUPHqS48K2uoF4kP22IaUzAbivXGVxm1EsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T01:15:28Z"
    mac: ENC[AES256_GCM,data:Qam8br87puVBluF7WE4JALnaFZUBmuo7j/E+vaq1peUvdRNLFNKiyCKKx8XCVJGlbSNlD+JoakQiedGr0xv2UXhulY0Stix77BktkxsQ9ydOmSbaE/B3wz//GToVFn5K0UizfFesWpVLassFHezBbhkgCvsa20htiYluNwnwRB8=,iv:wd3njN9X4OtSOK4moOAk+pmlRjfFG+x6vTjnNPCwrc8=,tag:0YHVbNAaLeuKLSq3TTzKrQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
