ansible_become_pass: ENC[AES256_GCM,data:xDa7ELaLJqy9QRkVdzo3Ug==,iv:X9uQ7Boa0TAeQcCd5QHCkQ0QjbTmR1vgORYm/a5OQYc=,tag:WXm0vDJwwMQLx4GSu7NVtg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcmcxZ1JVZVFHV29oOGN1
            MFVjVTZHOHpxOFRxZWJDOWhxRzIrbTA1SEVvCmF5U2VvczV5U2NoWnA2eGpHSlpq
            Uk9LQUxrUzlwall3dkhlYnpnSzZWT0kKLS0tIHZpM3RqbDYrVk1MS3QvczdyNmlC
            Tmk3R3JycklnUDBTUlRMang5cTZMTzgKBeXw0VEjju0fpnccV/xY/fykjuE3hYmb
            rC/e0ESNkYJ+2rOKG7Y7rM97ah3tFH1JDLizX3vJZ3Yi4bhkrtYvkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T02:04:18Z"
    mac: ENC[AES256_GCM,data:pBB3hAJy6hv/zIdZvSoumIspUsGsBF6XPgDAnP/fqY1pEWM1o85T1V1W6FROlDQNlfLtVfI91HdSfGjU6VR9ClGak6uRQLJKX1XsHPSRcQLFlXZgW0IQ6U80c+ywHe5cEsWr/Kna35m1IbnM+Y7TyzagYYtB7xfs3HAXRHzWljk=,iv:aeAhaaQ9/fSewNN7Y0f6GDXClluDHPg5uqrv/HJd0qI=,tag:C0yxEF5UcifmeDMa7z2+yA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
