---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: 2.18.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
  dependsOn:
    # This is how the PVC claim storage is auto provisioned.
    # https://github.com/rancher/local-path-provisioner
    - name: local-path-provisioner
      namespace: kube-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    admin:
      existingSecret: pihole-admin-secret
    ingress:
      annotations:
        hajimari.io/icon: simple-icons:pihole
        hajimari.io/url: https://pihole.patk.dev/admin
      enabled: true
      hosts:
      - pihole.patk.dev
      ingressClassName: internal
      tls:
      - hosts:
        - pihole.patk.dev

    persistentVolumeClaim:
      enabled: true
      storageClass: local-path
      size: 10Gi

    serviceDhcp:
      enabled: false

    # dig @192.168.3.14 hajimari.patk.dev
    serviceDns:
      enabled: true
      mixedService: true
      annotations:
        # Assign ip addresses to this service type.
        # https://docs.cilium.io/en/stable/network/lb-ipam/#loadbalancer-ip-address-management-lb-ipam
        io.cilium/lb-ipam-ips: "192.168.3.14"
      # Not able to query DNS from outside the
      # cluster unless set to 'Cluster'.
      externalTrafficPolicy: Cluster
      type: LoadBalancer

    # -- default upstream DNS 1 server to cloudflare
    DNS1: "1.1.1.1"
    # -- default upstream DNS 2 server to uquad9
    DNS2: "9.9.9.9"

    dnsmasq:
      upstreamServers:
        # Setup conditional forwarding to k8s-gateway for
        # the patk.dev domain. Creates an
        # /etc/dnsmasq.d/02-custom.conf file and populates with
          # addn-hosts=/etc/addn-hosts
          # rev-server=192.168.3.0/24,192.168.3.11
          # server=/patk.dev/192.168.3.11
          # server=//192.168.3.11
        # k8s network
        - rev-server=192.168.3.0/24,192.168.3.11
        - server=/patk.dev/192.168.3.11
        - server=//192.168.3.11
        # main
        - rev-server=192.168.1.0/24,192.168.1.1
        - server=/kaehuaea.local/192.168.1.1
        - server=//192.168.1.1
      customSettings:
        # Pihole was not evict an NXDOMAIN response from cache.
        # This lead to issues on network even when the gateway
        # was responding. We need this setting so pihole WILL
        # NOT cache NDSOMAIN responses in the future. Here's
        # an example entry '/var/log/pihole/pihole.log':
          # dnsmasq[270]: query[A] foo.mydomain.local from 1.2.3.4
          # dnsmasq[270]: cached foo.mydomain.local is NXDOMAIN
        - no-negcache

