apiVersion: v1
kind: Secret
metadata:
    name: pihole-admin-secret
    namespace: networking
stringData:
    admin-password: ENC[AES256_GCM,data:52MOPwDhR/gENofxEmMNBDYUFDw=,iv:ANvE+i5nG/OyTHt29GbrRwj5Hy3kVUUrySm6l2ysPpg=,tag:eYQobSZy/orXc42THr3KBA==,type:str]
    admin-user: ENC[AES256_GCM,data:WcMqFPA=,iv:PjaTYDwyZ62RL1bo2GqRRQqBZIAzINfcjzieIhW1daQ=,tag:RJsb5jaGzA0u4Ecod5u2Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aGxjekFuT1lVb05FTHht
            QzZyOWxBd2tZOXlwR0hnL29TMURqbEc3SlNBCmRJZURuV1MvYkM3eCtUTjhPam03
            cDBudGlGMU5CZEZLUlhPQldqdUU5RXcKLS0tIDUwUURXMkV0ZWk5ZTNiQ2lrb2Z5
            bVNCeVNHZjVuaHUvRmNZMU1vSmhLYXcKUVMnmzx5R8BTVO9nW0mZaGXo/vGCi3XU
            4JAWtKlpuFEhssSorkiuNz7ZRvZEX9euV/onjtj9GMTlZywsTaVKJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-19T21:13:45Z"
    mac: ENC[AES256_GCM,data:SiElnttkXeeBZDMsbC3TNDybu5oB2Jjoa+vq6q2DYlGJBNxUY+W5riMJEXJ337WbsPnHpRh7huUs5CaDPIdsZw+DegljM+dMFJlVkh4ZUzdy7IIQ3o2VEf0cs2QcSjZfHkrZH9RPexp/dioU+1xpX/D7G9n/6ltehUsJODnc1tU=,iv:BoTb8DzFK/yooczbxEDvR6ttjK2dUTN1+3BKs/cP35E=,tag:uLg0HlvQem7vnL1Zpu4H9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
