---
kubernetes:
  children:
    master:
      hosts:
        k8s-master-1:
          ansible_user: pat
          ansible_host: 10.0.80.2
    worker:
      hosts:
        k8s-worker-1:
          ansible_user: pat
          ansible_host: 10.0.80.5
        k8s-worker-2:
          ansible_user: pat
          ansible_host: 10.0.80.6
