apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:cOaHfvbZw3ybsWKE,iv:0FSte4oCc4MxXgG+n7dx2rREISB8zR66YQr4JD56S/w=,tag:PXqpuFyjOiLXeDJtxuHubg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZnUvZlFSTkpXaVcyaUZt
            VGVKdUJYNEpCNis5RXhMa0dQbGpGMU5hRFRBCnRXTkZCaEJiT0crbHg5STErSEpN
            aUZhcVFGTTArQUJCYmNwUWxERzEvREUKLS0tIExNOHgwdkhabTlOOEFIY1R1RlFq
            VzcyUlBzVkQ0SjhCNWhpQTZ3QklqVW8KQvp3HIHEfMo9BxOBdHLc4e8rMWg7y3Yq
            3rotymz4CoXndt5mHEmtINJRUtEReMfxb6WsTlnSSIiaGNcTODLXKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-17T02:04:47Z"
    mac: ENC[AES256_GCM,data:FfRwmEEXA5NRjQR0YVKjHB91bfYl1SXw0zNT664zQHFsuBdeUiK1qVxU9pI3NIcx5/+nvX3BlQ1HrQyoCBdV8FZUnvXdvpp3CwX8Il3wadzUKxADwTG6/V5X+KO+BpByzQ9TEHuSoW+98340Wc8annjKaaJvRm58t4P7AFVY5GY=,iv:Weoi+00OpI7BlmCZqQ/z1cKCLWkL3nC0+GM7hWp81Pg=,tag:WaItGE4bF9RdvzF5KMpJog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
