apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:Kjnp2TbQqbm2y58E,iv:sKiqQBm+1114VPu1V9db7P7rFgyjeZ3Q45G6qIEsqPk=,tag:buV6+Y7ijFubtyzguM+qxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRXFQNFYyOGg0MTQyK0JQ
            UHc3RzBad3pmTEg3UElzS0pBb25yYU1ZL0hRCjVCUk5ZcVhVZWpRVU1ZeFh0WUxh
            MC81eU1PdWVuQ3ZyZnRVT1V3NTVvV3cKLS0tIGNGMXRvZWpFS0RvcnRlK1llVDZD
            UlYzY1E5cnd4OVZzbUtwRHlOYVRtd2cKHGykZcpklykFTpwLitclwslSpJJdQz0L
            TSFy6i/6v5XRl7V23MdZy6wEHqBcwmyqm8p7pCidMwf6gddGDqUepg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-30T04:46:18Z"
    mac: ENC[AES256_GCM,data:3OxpQLYzcx4fox/EB4RBuJ3weXdviK/SRbzzIec8jVIoQopUeLVW917IRmJHo/ZYmoGMoJvLXiQsCfIhonnDL8GaDbnbfxkjYxc8BM7UnWjRl2zmtNFc3ThrhGKmEAzfnSwj13IG0Hc0g8INdseyBcoBt+b45RgCtUoREWDUUNM=,iv:8uTUXic87iKrgs1QSQ+ME62AqhkN8mTOF3RQAB00ng0=,tag:q+qLuFi8XCfLRpNukG3ccA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
