---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    account:
      valueFrom:
          secretKeyRef:
            name: cloudflared-secret
            key: AccountTag
    secret:
      tunnelId:
      valueFrom:
          secretKeyRef:
            name: cloudflared-secret
            key: TunnelSecret
    tunnelId:
      valueFrom:
          secretKeyRef:
            name: cloudflared-secret
            key: TunnelID
    tunnelName: k8s

    ingress:
        - hostname: "${SECRET_DOMAIN}"
          service: https://nginx-external-controller.networking.svc.cluster.local:443
          originRequest:
            originServerName: "external.${SECRET_DOMAIN}"
            http2Origin: true
            access:
              required: true
              teamName: patk-dev
              audTag:
                - aud1:
                    valueFrom:
                      secretKeyRef:
                        name: cloudflared-secret
                        key: AUDTag

        - hostname: "*.${SECRET_DOMAIN}"
          service: https://nginx-external-controller.networking.svc.cluster.local:443
          originRequest:
            originServerName: "external.${SECRET_DOMAIN}"
            http2Origin: true
            access:
              required: true
              teamName: patk-dev
              audTag:
                - aud1:
                    valueFrom:
                      secretKeyRef:
                        name: cloudflared-secret
                        key: AUDTag

        - service: http_status:404

    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 256Mi

    #   NO_AUTOUPDATE: "true"
    #   TUNNEL_CRED_FILE: /etc/cloudflared/creds/credentials.json
    #   TUNNEL_METRICS: 0.0.0.0:8080
    #   TUNNEL_TRANSPORT_PROTOCOL: auto
    # service:
    #   main:
    #     ports:
    #       http:
    #         port: 8080

    # TODO: Re-implement this serviceMonitor somehow.

    # serviceMonitor:
    #   main:
    #     enabled: true
    #     endpoints:
    #       - port: http
    #         scheme: http
    #         path: /metrics
    #         interval: 1m
    #         scrapeTimeout: 30s
    # probes:
    #   liveness: &probes
    #     enabled: true
    #     custom: true
    #     spec:
    #       httpGet:
    #         port: http
    #       timeoutSeconds: 1
    #   readiness: *probes
    #   startup:
    #     enabled: false
