---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cloudflare:
      secretName: cloudflare-cloudflare-tunnel
      tunnelName: k8s

      ingress:
        - hostname: "${SECRET_DOMAIN}"
          service: https://nginx-external-controller.networking.svc.cluster.local:443
          originRequest:
            originServerName: "external.${SECRET_DOMAIN}"
            http2Origin: true
            # A secrets ref won't work here, but flux can access
            # these environment variables. Set these
            # in the cluster-secrets-user.sops.yaml file.
            # These will require authentication through cloudflared
            # to any ingress request.
            access:
              required: true
              teamName: patk-dev
              audTag:
                - aud1 "${AUDTag1}"
                - aud2 "${AUDTag2}"

        - hostname: "*.${SECRET_DOMAIN}"
          service: https://nginx-external-controller.networking.svc.cluster.local:443
          originRequest:
            originServerName: "external.${SECRET_DOMAIN}"
            http2Origin: true
            access:
              required: true
              teamName: patk-dev
              audTag:
                - aud1 "${AUDTag1}"
                - aud2 "${AUDTag2}"
