---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    cloudflare:
      secretName: cloudflare-cloudflare-tunnel
      tunnelName: k8s

      ingress:
        - hostname: "${SECRET_DOMAIN}"
          service: https://nginx-external-controller.networking.svc.cluster.local:443
          originRequest:
            originServerName: "external.${SECRET_DOMAIN}"
            http2Origin: true
            # access:
            #   required: false
            #   teamName: patk-dev
            #   audTag:
            #     - aud1:
            #         valueFrom:
            #           secretKeyRef:
            #             name: cloudflare-cloudflare-tunnel
            #             key: AUDTag

        - hostname: "*.${SECRET_DOMAIN}"
          service: https://nginx-external-controller.networking.svc.cluster.local:443
          originRequest:
            originServerName: "external.${SECRET_DOMAIN}"
            http2Origin: true
            # access:
            #   required: false
            #   teamName: patk-dev
            #   audTag:
            #     - aud1:
            #         valueFrom:
            #           secretKeyRef:
            #             name: cloudflare-cloudflare-tunnel
            #             key: AUDTag

        - service: http_status:404
