apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
# This secret will become a volume
# mounted at /etc/cloudflared/creds/credentials.json.
stringData:
    credentials.json: ENC[AES256_GCM,data:p7BiBuXjW9eD3DBp4uAW6dOhPEKy2GAxqM92wY14cvMICR+C7SOoHDkjSslksbIQo/TViXattJuGYUkp0HzRZWvIoV2AgVLl9dXaq32WVse8HmGx0OzSebeMyyGPdWofyjpZsj3JzOlvyjfih5qr6HBRQ9qo7TazMjmAahz58F3ZtyEx4pqdjBV02s2/v78rdD965kkGbBlBXbglra8AxfOIydWF8UtSHUZ5lCVIq51IPCi0dHdsEDKiLLQB9F2DvNccKq/1jtOFEpyLVgJ+Jc3RnL44kgVQ4hUlof9rbmPFcrbXWnb+I7PTCeuOKGj+sCwENTQt5aaW,iv:dpPv/7ZmFV7cANaHMi830uE0rPx6rGxYRdQrTOXB5J0=,tag:mCiG6vYCGv4m+DfhiDid9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEa2NoMGN4eDhOSmQ2OXZY
            cm5LZzlGK1BrcjNSY1ovYmNualZuOFd0WkZBCjRqVTA1bW9heXlkSXhQTXBDc1NG
            RmNGUW1LdjBwbE1RL01WT3ltZWdkRjQKLS0tIE1ieHJEVTliTHpXUGpLTm4rTm5h
            N0VwVWllQkFVMDMyd3JVOFNxRVRjTjgKKMMS2jZSAoAlIHkpAM2Jh73tL1RVgMTi
            +daUk18nRYHbQkcq5hViExD4Cqbd8SzCYThxS73TZht1ihvz8M0sGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-20T19:46:45Z"
    mac: ENC[AES256_GCM,data:jleBPwFdqRBt54GErFfAKI3p808e3ijzRB+BxrA4aHViUD8nud40UcZdPKormnTqNx718VPVjb3bLpcxCGLTedobXeW06ziNQ4bRqDm2hMi0jO8annxhKOF5Ukvn9LkrH5D2nQLPRu5FT8IqL+OkWROkKqOuhLjiZXtqAHdtahg=,iv:kP2J+jOfmplQB+3baQMqpqj6Tboo/R4nRcoeZIvYKdA=,tag:/Otn/862BA2IdsehwvxHGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
