apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:RPgLjFkoGDFnl/Z5EKspPBYdWNrUWksfOuBoPyTkYceCfW7O,iv:HdHBL58vmVWYPMx741eBrusSGbJG47ocGV3lAXyTrmQ=,tag:5IZ+1EneHeQeNOK8bV7pzw==,type:str]
    credentials.json: ENC[AES256_GCM,data:wUzM4/m5rXV045eIz58xGMZg33yy2fXUBsRSz895Bo+6fJt8w4Dj17hKCLv6Ibv6cH6MDY5KB2Ey/OT8CNwTP3ono6KRMdJGrOlxUKQteewgJU/U9nYdXmJMJou3YzETU8ufAYiLBoynuEJ/kDbx0ezz5B5zikAPN4l1Nl/RB4EZI8aJuu1AAjE17eUHBbPKt4jmHofB3CquVuTLACiDlOp8A3l4ydkNzohEsvtYbw==,iv:tyz7fdk51mysiAt9KnUwz/XqFZjtsp8zIWMc6twiVqs=,tag:0ZbXYz8IQu2lmayj80UAuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19teh088u80fevs4tja0pyammvuuznznlejwz6xtnfujj6e238amsyy0jef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcnVUU2cyNXlOYmFpRlMv
            SEExTEVKVWtadzlyeDJObnVYZ2d5eXJpNlMwCnJvdUdORXpGbUxwVU5iMUwvQkJU
            eFR6SXQ4TkorOWQ1NEg2NW4rT3BudlEKLS0tIGdaNkY1Qm8zdC9kWVdUM1hBeERV
            K3BkWFM0YXNXUjEzYm5rckszTzdDRTQKzTVHx0VMDM9l49nqCW7J4UWsLpG91264
            FTNzb8uK7oM1wZueTr4rT+qdmo5izhPF9H/6ii/FNPpz1n8whdD92g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T05:13:31Z"
    mac: ENC[AES256_GCM,data:xJk3ovDzwImwPXauKIM/PzRCITbONsTbwHtcaDvvu7dV0Htt2kJzHbIh1cT3th8pu9vJd74gGf/D3WI2LzAVDGrL4yMcWPATBq1AgFnMEkUx4+OYTgJQxUgY6KESxs0BlVT8olg6vFMp69d+p1r8Jmsr6xkNtTOORM2oZHtsGck=,iv:BCh7C0YOwftt/fTPazJIzPFtLIplSHIQphzSqQI7AME=,tag:Eu51cEuqeAaMt/DglMGQkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
